### ISSUE TITLE
DepthMap Preprocessor setting values have no effect.

### ISSUE THREAD

**Issue by fambaa** [Fannovel16/comfy_controlnet_preprocessors#10]
I was playing around with this preprocessor and I noticed that the settings actually don't do anything.
The depth map doesn't change one bit, turning a or bg threshold completely up or down does nothing.
It is the same depth map.

Or am I doing something wrong? Am I missing something?

**Comment by Fannovel16** [comment]
You can connect that node to the PreviewImage node to see the depth map result. If it is a blank black image then the preprocessor can't make depth map from your image.

**Comment by fambaa** [comment]
![Screenshot 2023-03-23 104837](https://user-images.githubusercontent.com/128101183/227165494-246ce2b9-25d2-445c-aaea-2911a0374ccf.png)
These all look identical or I am tripping. Does the Midas Preproc not work similar to the leres Depth which is in auto1111?
If not, would that be possible to do?
Right now I am controlling the depth with manipulating the brightness after the fact.
Ty in advance.

**Comment by Fannovel16** [comment]
> These all look identical or I am tripping.

a and bg_threshold are hardcoded in the webui and original controlnet repo. So maybe changing these values isn't nessasery.

> Does the Midas Preproc not work similar to the leres Depth which is in auto1111?
Midas and Leres are two different preprocessors. I will try to add it to this repo ASAP.

**Comment by fambaa** [comment]
The leres one is superior because it has foreground and background thresholds, and imo that is pretty useful, if it works. Even now, look what I am able to do now with the help with controlnet and your preprocs, and a new mask node someone did just a few hours ago.
![Screenshot 2023-03-23 110131](https://user-images.githubusercontent.com/128101183/227169546-b3843512-d575-4c32-b1e8-8dadd21753ab.png)

I can basically remove the background and replace it with noise or any background color, that should make scenes that are composited much more coherent because you can just add a background later or inbetween without having the subject generation and any colors you specify for clothing or whatnot bleed into the background colors which happens all the time.
Same prompt when I tell it for example to draw a demon the background will be red and black same prompt just changed to angel it will be shiny and golden. With controlnets I can basically remove the background in a few steps :)

Im basically turning the depth map into a mask, so it needs to stick to the subject pretty closely, its not as accurate, sometimes it fills supposed holes with foreground, but its alright for now.

**Comment by Fannovel16** [comment]
Do you enable "optimized monocular depth estimation" option in the webui? Idk about it and is there anyone use it.

**Comment by fambaa** [comment]
You mean in automatic? Yeah its enabled for me, although I never tried to use automatic of controlnets like this. Reproducing what I did with a single workflow in comfy would take 2 or 3 steps, plus exporting the depth map to GIMP or something to make a proper mask out of it.
In the above example you can see that the depth map of the hair is a little bit too dark. Now I can change that with upping the brightness with a filter a bit, but then other bits that aren't supposed to be in the mask might get picked up.

It probably will never be exact cutout, but it is miles better what I had before in terms of keeping the image. Before I had an extremely hacky way of removing background, and I don't even understand why that one works like it does as you can see here.

Still pretty interesting and extremely clean subject/background seperation but the image is completely changed ;)
Maybe you can make sense of what is actually happening there. 
https://civitai.com/models/22651/comfyui-workflow-remove-background

Anyways, Im rambling lol

**Comment by Fannovel16** [comment]
I have just added LeReS depth at https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/869fcb7c73089ef55af7f96425213d22d0dfe546
