### ISSUE TITLE
Instalation fail

### ISSUE THREAD

**Issue by AbyszOne** [Fannovel16/comfy_controlnet_preprocessors#14]
Installing requirements...
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.7.0.72-cp37-abi3-win_amd64.whl (44.9 MB)
Requirement already satisfied: opencv-python in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from -r F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 2)) (4.7.0.72)
Collecting timm==0.6.12
  Downloading timm-0.6.12-py3-none-any.whl (549 kB)
     ---------------------------------------- 549.1/549.1 kB 6.8 MB/s eta 0:00:00
Requirement already satisfied: torchvision in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from -r F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 4)) (0.15.1)
Requirement already satisfied: scipy in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from -r F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 5)) (1.10.1)
Requirement already satisfied: matplotlib in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from -r F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 6)) (3.7.1)
Requirement already satisfied: scikit-image in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from -r F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors/requirements.txt (line 7)) (0.20.0)
Collecting prettytable==3.6.0
  Downloading prettytable-3.6.0-py3-none-any.whl (27 kB)
Collecting svglib
  Using cached svglib-1.5.1.tar.gz (913 kB)
  Preparing metadata (setup.py) ... done
Collecting reportlab
  Downloading reportlab-3.6.12-cp311-cp311-win_amd64.whl (2.3 MB)
     ---------------------------------------- 2.3/2.3 MB 11.5 MB/s eta 0:00:00
Collecting addict
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting yapf
  Using cached yapf-0.32.0-py2.py3-none-any.whl (190 kB)
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\install.py", line 38, in <module>
    add_global_shortcut_module()
  File "F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\install.py", line 20, in add_global_shortcut_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from . import canny, hed, midas, mlsd, openpose, uniformer, leres, mp, color, binary, pidinet
  File "F:\AIUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\hed\__init__.py", line 7, in <module>
    import model_management
ModuleNotFoundError: No module named 'model_management'

**Comment by Fannovel16** [comment]
Fixed at commit https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/f32cc8870031f77cf5ab33a7e4964a13a3be8a07
