### ISSUE TITLE
ComfyUI can't import comfy_controlnet_preprocessors.

### ISSUE THREAD

**Issue by nutellaToast** [Fannovel16/comfy_controlnet_preprocessors#16]
```
File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\__init__.py", line 1, in <module>
    from . import canny, hed, midas, mlsd, openpose, uniformer, leres, mp, color, binary, pidinet
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors\canny\__init__.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_controlnet_preprocessors module for custom nodes: No module named 'cv2'
```

That's the message I get after opening ComfyUI. Got all the dependencies and everything but still not working.

**Comment by Fannovel16** [comment]
Did you run install.py or pip install? If so then maybe there were some problems when installing dependencies

**Comment by nutellaToast** [comment]
I ran install.py
![image](https://user-images.githubusercontent.com/39800979/227793684-fb96d715-9cd3-4359-83b0-1d17bfa123e1.png)
![image](https://user-images.githubusercontent.com/39800979/227793694-cfb7bbd2-3a58-42f5-bc0f-e9b606b3958c.png)

**Comment by Fannovel16** [comment]
I think you ran the wrong command. It seems like you are using the standalone build so the right one is `..\..\..\python_embeded\python.exe install.py`

**Comment by nutellaToast** [comment]
There's no install.py within ..\python_embeded.
Not that it now matters for me. I copied all of the needed stuff manually from ..\Programs\Python\Python310\Lib\site-packages
