### ISSUE TITLE
Error when running install.py

### ISSUE THREAD

**Issue by XiPoWnZX** [Fannovel16/comfy_controlnet_preprocessors#18]
<img width="552" alt="error" src="https://user-images.githubusercontent.com/69403071/228059427-6a66de49-2eca-4797-a24d-dd363bcb6dd9.png">

French part is : 'C:\Users\P-A' is not recognized as an internal or external command, executable program or batch file.

(I wasnt able to give code written as its closing directly when it finish)
I dont really have good knowledge in all that and don't understand all this meaning

**Comment by Fannovel16** [comment]
Can you try to reclone this repo and run install.py again? I just updated it and think it may solves your problem.

**Comment by rauldlnx10** [comment]
I have the same issue, i did git pull but still have the same issue.

**Comment by rauldlnx10** [comment]
The problem is the standalone installation of python in comfyui, you can solve it doing this:

change path/to/ComfyUI/python_embeded/ with your python_embended folder in your ComfyUI folder.
/path/to/ComfyUI/python_embeded/python.exe -m pip install --upgrade --force-reinstall opencv-python
/path/to/ComfyUI/python_embeded/python.exe -m pip install --upgrade --force-reinstall scikit-image
/path/to/ComfyUI/python_embeded/python.exe -m pip install --upgrade --force-reinstall addict

and do the same with every module who give you an import module error.

**Comment by spikeliu1984** [comment]
I have similar problem when running install.py in ComfyUI portable, by following instructions I got error says something like install.py does not exist, but I can see it inside the folder.
I tried what @rauldlnx10 said and also tried something I saw on other custom node github: /path/to/ComfyUI/python_embeded/python.exe -m pip install -r requirements.txt
After those steps I can see the preprocessor category inside comfyUI, but there are only 'edge line', 'pose', 'normal depth map', 'semseq' and 'color style', it's obviously incomplete. 
In the confyUI console, it shows ```
File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Workflows\__init__.py", line 1, in <module>
    from . import canny, hed, midas, mlsd, openpose, uniformer
ImportError: cannot import name 'canny' from 'Workflows' (E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Workflows\__init__.py)

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Workflows module for custom nodes: cannot import name 'canny' from 'Workflows' (E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Workflows\__init__.py)
```
I guess I'm still missing canny, hed, midas, mlsd, openpose and uniformer? 
I don't know python works at all, please let me know how can I install other dependencies, I tried adding those names I don't have inside requirements.txt and run -m pip install -r requirements.txt, I remember it says no distribution of name canny or something like that. Please help. Thanks.

**Comment by Fannovel16** [comment]
Or you can use /path/to/ComfyUI/python_embeded/python.exe install.py

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/b8a108a0f8ae37b9302b32d7c236cfa3dde97920
