### ISSUE TITLE
Error when running install.py: top_pool_forward

### ISSUE THREAD

**Issue by wallish77** [Fannovel16/comfy_controlnet_preprocessors#20]
When attempting to run install.py on a linux system, I get the following error:

`AssertionError: top_pool_forward miss in module _ext`

It looks like it's a problem with `corner_pool.py` under `mmcv`.  I have done a git pull to the newest version and seen no change.

**Comment by FaridSafi** [comment]
+1

**Comment by Fannovel16** [comment]
The mmcv package on your machine don't have top_pool_forward for some reasons. Can you try to reinstall it?

**Comment by FaridSafi** [comment]
I had to `pip uninstall mmcv` to fix my issue. Also I had to install CUDA version 11.7

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/8a654cb3e039ed5106f8e7e507edd0634cc5f478
