### ISSUE TITLE
[FEATURE REQUEST] Face Mesh Preprocessor as mask

### ISSUE THREAD

**Issue by MoonMoon82** [Fannovel16/comfy_controlnet_preprocessors#29]
Would it be possible to add an option to fill the output of the face outline so it can be used as a mask?
Could be great to use it as latent / inpainting mask !

**Comment by Fannovel16** [comment]
Not really. The role of preprocessor nodes is only generating hint images for ControlNet. You will need another custom node processing output from that node. It is out of scope of this repo. But you can ask people [Matrix space: #comfyui_space:matrix.org](https://app.element.io/#/room/%23comfyui_space%3Amatrix.org) to make one.
