### ISSUE TITLE
pidinet_v1 in install

### ISSUE THREAD

**Issue by Ishino** [Fannovel16/comfy_controlnet_preprocessors#36]
From the last commit, the pidinet_v1 model has been removed, but it's still in the install.py code and this brakes the install. Was the removal intentionally?

Thanks

**Comment by pham-nhat-khanh** [comment]
if anyone is stuck then comment out + remove pidinet_v1 from the import statement
`
--- a/install.py
+++ b/install.py
@@ -28,7 +28,7 @@ def download_models():
     openpose_v1.OpenposeDetector()
     uniformer.UniformerDetector()
     leres.download_model_if_not_existed()
-    pidinet_v1.download_if_not_existed()
+    # pidinet_v11.download_if_not_existed()
     zoe.ZoeDetector()
     normalbae.NormalBaeDetector()
     hed_v11.ControlNetHED_Apache2()
@@ -47,7 +47,7 @@ if args.no_download_ckpts: exit()
 add_global_shortcut_module("cli_args", os.path.join(EXT_PATH, "../../comfy/cli_args.py"))    
 add_global_shortcut_module("model_management", os.path.join(EXT_PATH, "../../comfy/model_management.py"))
 add_global_shortcut_module(this_module_name, os.path.join(EXT_PATH, "__init__.py"))
-from comfy_controlnet_preprocessors.v1 import canny, hed_v1, midas, mlsd, openpose_v1, uniformer, leres, pidinet_v1
+from comfy_controlnet_preprocessors.v1 import canny, hed_v1, midas, mlsd, openpose_v1, uniformer, leres
 from comfy_controlnet_preprocessors.v11 import zoe, normalbae, hed_v11, pidinet_v11
 print("Download models...")
 sleep(2)
 `

**Comment by Fannovel16** [comment]
I forgot to edit it to pidinet_v11 😅

**Comment by Fannovel16** [comment]
I forgot to remove that line in install.py. My bad. Fixed at https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/fb0ef7ff1230659cca10e2825934b9a48fb5aeef
