### ISSUE TITLE
[FIX]: Tile Preprocessor + Pidinet_v1 files

### ISSUE THREAD

**Issue by paulo-coronado** [Fannovel16/comfy_controlnet_preprocessors#37]
Hello @Fannovel16! I hope you’re doing well. I wanted to thank you for your amazing work on the nodes - they’re the best!

I was trying to use **Tile Preprocessor** today but it’s not showing up on the UI. I ran `git pull` and then `install.py`, but it still isn’t working. Could you please help me with this?

Also, when I ran `install.py`, I got an error saying that `v1/pidinet_v1` does not exist. It seems that you removed the files in a previous commit. I’m not sure if the import should be removed or if the files should be restored… could you please advise me on this?

Thank you so much for your help!

**Comment by Fannovel16** [comment]
I forgot to remove that line in install.py. My bad. Fixed at https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/fb0ef7ff1230659cca10e2825934b9a48fb5aeef

**Comment by paulo-coronado** [comment]
@Fannovel16, could you please reopen the issue? Because, I don't think the Tile Preprocessor node has not been implemented yet. Thanks :)
