### ISSUE TITLE
Install doesn't install

### ISSUE THREAD

**Issue by aaron9412** [Fannovel16/comfy_controlnet_preprocessors#44]
Hi, thank you for creating this.
I have tried running install.sh, install.bat, and install.py and I can still see no new nodes.
I'm not sure what details to provide.
I am using a standalone copy of comfy, windows 10, and comfy runs just fine.
I first tried running install.py (because I'm dumb and didn't read about the standalone).
After that I tried running the other two. 
I have restarted comfy, and I am looking for "open" or "pose" in the nodes and see nothing.
The install.sh did not close, but I don't see any code inside of it to make it (I left it running for about an hour).
I renamed the folder from "comfy_controlnet_preprocessors" to just "preprocessors" but I don't see where that would be an issue.
Please advise.
And again, thank you.
-Aaron

**Comment by cyldsyp1** [comment]
![image](https://user-images.githubusercontent.com/84093070/236523447-46551ee7-757c-49f7-acd1-febbb706be02.png)
modify intall.py

replace 
command += '-s'
with
command.append('-s')

**Comment by aaron9412** [comment]
Ah! Thank you, I will try that when I get home.
I thought it was a problem with my PIP but I'm dumb and don't know how to subprocess or -m.

For anyone else who reads this, this changes the variable ***command*** from 

['C:\\WhereYouRanPython\\python.exe', `'-', 's',` '-m', 'pip', 'install', '-r', 'K:/YourRequirementsFolder/requirements.txt', '--extra-index-url', 'https://download.pytorch.org/whl/cu117', '--no-warn-script-location']

to 

['C:\\WhereYouRanPython\\Python39\\python.exe', `'-s',` '-m', 'pip', 'install', '-r', 'K:/YourRequirementsFolder/requirements.txt', '--extra-index-url', 'https://download.pytorch.org/whl/cu117', '--no-warn-script-location']

Also I didn't see it at first but comfyui command prompt window showed errors on startup that I was missing the requirements. Will be good for me to look there first next time.
