### ISSUE TITLE
Google Colab Usage

### ISSUE THREAD

**Issue by atdigit** [Fannovel16/comfy_controlnet_preprocessors#46]
Hi. Thanks for the valuable development. Could you add instructions to the installation section on how to use this with Google Colab?

**Comment by Fannovel16** [comment]
Just do a git clone then run `python install.py`

**Comment by Fannovel16** [comment]
If you use ComfyUI's official [colab notebook](https://colab.research.google.com/github/comfyanonymous/ComfyUI/blob/master/notebooks/comfyui_colab.ipynb), you can just uncomment this line:
```
#!cd custom_nodes && git clone https://github.com/Fannovel16/comfy_controlnet_preprocessors; cd comfy_controlnet_preprocessors && python install.py
```

**Comment by Fannovel16** [comment]
I just tested that notebook. It couldn't be installed because of reportlab. I removed it.

**Comment by atdigit** [comment]
Thank you for quick reaction and nice update.
