### ISSUE TITLE
No module named 'mediapipe'

### ISSUE THREAD

**Issue by danzelus** [Fannovel16/comfy_controlnet_preprocessors#53]
Installed media pipe 0.9.1.0,  0.9.2.1,  0.9.3.0,  0.10.0. Always same issue

![2023-05-21_04-20-17](https://github.com/Fannovel16/comfy_controlnet_preprocessors/assets/20360260/43f4f072-ca2a-4cef-91a2-72f5842d2d54)

**Comment by ryo0ka** [comment]
same

**Comment by ryo0ka** [comment]
@danzelus i fixed it. run the following command before `install`

`pip install -r .\requirements.txt --user`

**Comment by danzelus** [comment]
> @danzelus i fixed it. run the following command before `install`
> 
> `pip install -r .\requirements.txt --user`

solved
