### ISSUE TITLE
ModuleNotFoundError: No module named 'einops'

### ISSUE THREAD

**Issue by boricuapab** [Fannovel16/comfy_controlnet_preprocessors#7]
When installing the comfy preprocessors I got this error:

![comfyPreprocessorsInstallIssue](https://user-images.githubusercontent.com/61924816/226153527-95cbc31e-cdc0-4d8f-b009-187db3df00f3.PNG)

**Comment by Fannovel16** [comment]
You have to install dependencies of comfyui before installing dependencies of this extension. I forgot to include that to readme.

**Comment by boricuapab** [comment]
Ok, thanks for the reply, I've now installed the comfyui requirements.txt
