### ISSUE TITLE
No module named 'prettytable' Issue

### ISSUE THREAD

**Issue by boricuapab** [Fannovel16/comfy_controlnet_preprocessors#8]
When launching comfyui, I get this error, and in comfyui I am unable to create any of the preprocessor nodes.

![noModuleNamedPrettyTable](https://user-images.githubusercontent.com/61924816/226195619-d30e39fc-264d-4d0a-84b0-685b227e9a1c.PNG)

**Comment by Fannovel16** [comment]
Did you run install.py script?

**Comment by boricuapab** [comment]
Working now, I was using git clone method for comfyui, but have now re-installed the portable version and now installing the control net pre-processors works
