### ISSUE TITLE
MiDaS Issues with auto scaling

### ISSUE THREAD

**Issue by eldragon0** [Fannovel16/comfy_controlnet_preprocessors#9]
After getting this installed and running really well from what I can tell, Great JOB!  I noticed that M-LSDPreprocessor, MiDaS Depth Map, and Normal Map, all fail to return outputs with images that don't fall into 64x * 64x aspect ratios.  the auto scale appears to work for the rest of the control nets. If I run my image through the images scaler first and upscale to a 64x ratio and center it it works fine. So it appears that the issue is just auto scaling.

**Comment by Fannovel16** [comment]
My bad. I put resize_image function in the wrong places. Fixed in https://github.com/Fannovel16/comfy_controlnet_preprocessors/commit/d6a630f4a7d8973287ac3f44a509ff16342844d0
